version: 2
updates:
 - package-ecosystem: "maven"
   directory: "/hospital-scheduler-aggregator"
   schedule:
     interval: "daily"
   open-pull-requests-limit: 10
   groups:
     maven-plugin-updates:
       patterns:
        - "org.apache.maven.plugins:*"
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: "weekly"
