services:
  hospital-java-app:
    build:
      context: ..
      dockerfile: docker-build-run/Dockerfile
      args:
        DISPLAY: ${DISPLAY}
    environment:
      - DISPLAY=${DISPLAY}
      - _JAVA_AWT_WM_NONREPARENTING=1
      - SUN_AWT_DISABLE_OPENGL=true
    container_name: hospital_java_app
    restart: "no"
    networks:
     - hospital_java_network
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  hospital_java_network:
    driver: bridge