services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: "no"
    ports:
      - "27017:27017"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    volumes:
      - mongo-data:/data/db
    networks:
      - hospital_java_network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mongo-init-replica:
    image: mongo:5
    container_name: hospital_mongo_init
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    networks:
     - hospital_java_network
    entrypoint:
      - bash
      - -c
      - |
        echo 'Waiting on MongoDB init'
        mongo --host mongodb:27017 --eval '
          var status = rs.status()
          if (status.ok === 1) {
            print("Replica Set already configured");
          } else {
            rs.initiate({
              _id: "rs0",
              members: [{ _id: 0, host: "mongodb:27017" }]
            });
            print("Replica Set rs0 initialized");
          }
        '

  hospital-java-app:
    depends_on:
      mongo-init-replica:
        condition: service_completed_successfully
    command:
        [
          "java",
          "-jar",
          "/app/app.jar",
          "--mongo-connection-string=mongodb://mongodb:27017/?replicaSet=rs0",
          "--db-mongo-name=hospital_docker_mongo",
          "--db-mongo-doctor-collection=doctor_docker_mongo",
          "--db-mongo-department-collection=department-docker_mongo",
          "--db-mongo-shift-collection=shift-docker_mongo"
        ]

volumes:
  mongo-data: