<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.duckdns.whocaresleft</groupId>
    <artifactId>hospital-scheduler-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../hospital-scheduler-parent</relativePath>
  </parent>
  <artifactId>hospital-scheduler-report</artifactId>
  <packaging>pom</packaging>
  
  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>hospital-scheduler-domain</artifactId>
    </dependency>
    
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>hospital-scheduler-presentation</artifactId>
    </dependency>
  </dependencies>
  
  <profiles>
    <profile>
      <id>jacoco</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>report-aggregate</id>
                <phase>verify</phase>
                <goals>
                  <goal>report-aggregate</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    
    <profile>
      <id>coveralls</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>report-aggregate</id>
                <phase>verify</phase>
                <goals>
                  <goal>report-aggregate</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          
          <plugin>
            <groupId>com.github.hazendaz.maven</groupId>
            <artifactId>coveralls-maven-plugin</artifactId>
            <configuration>
              <jacocoReports>
                <param>${project.build.directory}/site/jacoco-aggregate/jacoco.xml</param>
              </jacocoReports>
              <sourceDirectories>
                <param>${project.basedir}/../hospital-scheduler-domain/src/main/java</param>
                <param>${project.basedir}/../hospital-scheduler-presentation/src/main/java</param>
              </sourceDirectories>
            </configuration>
            <executions>
              <execution>
                <phase>verify</phase>
                <goals>
                  <goal>report</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>