<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.duckdns.whocaresleft</groupId>
  <artifactId>hospital-scheduler-aggregator</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <modules>
    <module>../hospital-scheduler-bom</module>
    <module>../hospital-scheduler-parent</module>
    <module>../hospital-scheduler-domain</module>
    <module>../hospital-scheduler-presentation</module>
  </modules>
  
  <profiles>
    <profile>
      <id>app</id>
      <modules>
        <module>../hospital-scheduler-app</module>
      </modules>
    </profile>
    
    <profile>
      <id>jacoco</id>
      <modules>
        <module>../hospital-scheduler-report</module>
      </modules>
    </profile>
    
    <profile>
      <id>coveralls</id>
      <modules>
        <module>../hospital-scheduler-report</module>
      </modules>
    </profile>
  </profiles>
</project>