<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.duckdns.whocaresleft</groupId>
  <artifactId>hospital-scheduler-aggregator</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    
    <maven.sonar.version>5.6.0.6792</maven.sonar.version>
    <sonar.host.url>http://localhost:9000</sonar.host.url>
    <sonar.tests>
      src/test/java,
      <!--src/it/java, --> 
      <!--src/e2e/java, these are not present yet  --> 
    </sonar.tests>
    <sonar.junit.reportPaths>
      target/surefire-reports,
      target/failsafe-reports
    </sonar.junit.reportPaths>
    <sonar.coverage.exclusions>
      **/model/Doctor.*,
      **/exception/*.*,
      **/learning/*.*
    </sonar.coverage.exclusions>
    <sonar.organization>whocaresleft</sonar.organization>
  </properties>

  <modules>
    <module>../hospital-scheduler-bom</module>
    <module>../hospital-scheduler-parent</module>
    <module>../hospital-scheduler-domain</module>
    <module>../hospital-scheduler-presentation</module>
  </modules>
  
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.sonarsource.scanner.maven</groupId>
          <artifactId>sonar-maven-plugin</artifactId>
          <version>${maven.sonar.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    
    <plugins>
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
  
  <profiles>
    <profile>
      <id>app</id>
      <modules>
        <module>../hospital-scheduler-app</module>
      </modules>
    </profile>
    
    <profile>
      <id>jacoco</id>
      <modules>
        <module>../hospital-scheduler-report</module>
      </modules>
    </profile>
    
    <profile>
      <id>coveralls</id>
      <modules>
        <module>../hospital-scheduler-report</module>
      </modules>
    </profile>
  </profiles>
</project>