name: Java CI with Maven in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: hospital-scheduler-aggregator
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    strategy:
      matrix:
        java: [17, 21] 

    name: Build with Java ${{ matrix.java }} on Linux
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set Maven additional options
        run: |
          echo "CODE_COVERAGE_ADDITIONAL_OPTIONS=-Pcoveralls" >> $GITHUB_ENV
        if: ${{ env.COVERALLS_REPO_TOKEN != '' && matrix.java == 17 }}

      - name: Pre-pull testcontainers Docker images
        run: |
          docker pull mariadb:10.3.39
          docker pull mongo:5
          docker pull testcontainers/ryuk:0.12.0

      - name: Setup sonarcloud eventual goal
        run: |
          echo "SONARGOAL=org.sonarsource.scanner.maven:sonar-maven-plugin:sonar" >> $GITHUB_ENV
        if: ${{ env.SONAR_TOKEN != '' && matrix.java == 17 }}

      - name: Install Xvfb and OpenBox
        run: |
          sudo apt-get update && sudo apt-get install -y openbox xvfb

      - name: Build with Maven and SonarCloud
        run: |
          xvfb-run -a -s "-screen 0 1920x1080x24" bash -c "
          openbox &
          ./mvnw verify $CODE_COVERAGE_ADDITIONAL_OPTIONS $SONARGOAL \
          -f ${{ env.workdir }}/pom.xml \
          -Dsonar.organization=whocaresleft \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=whocaresleft_hospital-scheduler"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Generate JUnit report
        run: >
          ./mvnw surefire-report:report-only -f ${{ env.workdir }}/pom.xml
        if: ${{ always() }}
      
      - name: Archive JUnit report
        uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/reports'
