name: Java CI with Maven in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: hospital-scheduler-aggregator
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    strategy:
      matrix:
        java: [17, 21]

    name: Build with Java ${{ matrix.java }} on Linux
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set Maven additional options
        run: |
          echo "CODE_COVERAGE_ADDITIONAL_OPTIONS=-Pcoveralls" >> $GITHUB_ENV
        if: ${{ env.COVERALLS_REPO_TOKEN != '' && matrix.java == 17 }}

      - name: Setup sonarcloud eventual goal
        run: |
          echo "SONARGOAL=org.sonarsource.scanner.maven:sonar-maven-plugin:sonar" >> $GITHUB_ENV
        if: ${{ env.SONAR_TOKEN != '' && matrix.java == 17 }}

      - name: Build with Maven and SonarCloud
        run: >
          xvfb-run mvn verify $CODE_COVERAGE_ADDITIONAL_OPTIONS $SONARGOAL
          -Dsonar.organization=whocaresleft
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=whocaresleft_hospital-scheduler
        working-directory: ${{ env.workdir }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Generate JUnit report
        run: >
          mvn surefire-report:report-only
        working-directory: ${{ env.workdir }}
        if: ${{ always() }}
      
      - name: Archive JUnit report
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/reports'
